export const projectsData = [
  {
    id: 1,
    title: "LDM Site",
    description: "Project 1 description",
    image: "https://res.cloudinary.com/devrbr7ot/image/upload/v1701423191/ldmuinbdg-com-1024x768desktop-c9247b_rani8y.jpg",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/riyyanfirdaus/eldeemsite",
    previewUrl: "https://eldeem.vercel.app/",
  },
  {
    id: 2,
    title: "PuasaQ",
    description: "Project 2 description",
    image: "https://res.cloudinary.com/devrbr7ot/image/upload/v1701423192/puasaq-netlify-app-1024x768desktop-9305d4_pk4evs.jpg",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/riyyanfirdaus/ramadhan-planner-v3",
    previewUrl: "https://puasaq.netlify.app/",
  },
  {
    id: 3,
    title: "KosKeun",
    description: "Project 3 description",
    image: "https://res.cloudinary.com/devrbr7ot/image/upload/v1701423192/koskeunproject-netlify-app-1024x768desktop-967856_stxcch.jpg",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/riyyanfir/koskeun",
    previewUrl: "https://koskeunproject.netlify.app/",
  },
  {
    id: 4,
    title: "Food Ordering Application",
    description: "Project 4 description",
    image: "/images/projects/4.png",
    tag: ["All", "Mobile"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 5,
    title: "React Firebase Template",
    description: "Authentication and CRUD operations",
    image: "/images/projects/5.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 6,
    title: "Full-stack Roadmap",
    description: "Project 5 description",
    image: "/images/projects/6.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
  },
];
